"""Add chain and indexes for scalability

Revision ID: 25dbae2529f9
Revises: 67e50bb827d6
Create Date: 2025-11-29 23:36:13.879162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25dbae2529f9'
down_revision = '67e50bb827d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chain', sa.String(length=20), nullable=True))
        batch_op.create_index('idx_user_coin_chain', ['user_id', 'coin_id', 'chain'], unique=False)

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index('idx_user_coin_chain')
        batch_op.drop_column('chain')

    # ### end Alembic commands ###
