"""Initial migration

Revision ID: 67e50bb827d6
Revises: 
Create Date: 2025-11-29 20:26:48.305986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e50bb827d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('coin_id', sa.String(length=64), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('last_change_pct_1h', sa.Float(), nullable=True),
    sa.Column('last_change_pct_24h', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('coin_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliq_user_id', sa.String(length=64), nullable=False),
    sa.Column('default_channel_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliq_user_id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('coin_id', sa.String(length=64), nullable=True),
    sa.Column('price_change_pct', sa.Float(), nullable=True),
    sa.Column('alert_message', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('coin_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holdings')
    op.drop_table('alerts')
    op.drop_table('users')
    op.drop_table('prices')
    # ### end Alembic commands ###
